apiVersion: v1
kind: Service
metadata:
  name: register-service
spec:
  selector:
    app: register
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30081   # changed from 30080 to 30081
